theme: jekyll-theme-minimal
title: HabiTech: Inhabiting Buildings, Data \& Technology
description: A workshop at CHI2020 to help define new research area: A building-level counterpart to digital civics.
