theme: jekyll-theme-minimal
title: HabiTech Inhabiting Buildings, Data and Technology
description: A workshop at CHI2020 to help define new research area - A building-level counterpart to digital civics.
